### ISSUE TITLE
Create client-side route to edit food + add Link in FoodDetails component

### ISSUE THREAD

**Issue by bryceknz** [pohutukawa-2019/foodlist#13]
Blocked by #14 

We need a client-side route to show the `EditFood` component (talk to your lead developer if this component hasn't been created yet!).

Create a route in the `App` component to render the `EditFood` component at `/edit/:foodId`.

Use this route as a link in the FoodDetails component to allow the user to be taken to the component where they can edit a food.

**Comment by don-smith** [comment]
The client-side route has been created and is in `dev`, but there is no link in the `FoodDetails` component. Moving back to in progress.
