### ISSUE TITLE
Create a thunk action to get foods from a given category name

### ISSUE THREAD

**Issue by bryceknz** [pohutukawa-2019/foodlist#21]
This ticket will require several action creators to be created. You will need an async (thunk) action that can dispatch `GET_CATEGORY_PENDING`, `GET_CATEGORY_SUCCESS`, and `ERROR` actions - each will need their own action creator.

The thunk action will dispatch a `getCategoryPending` action, then make an API request to `/api/v1/foods/category/:name`. If the request is successful, dispatch a `getCategorySuccess` action. If the request fails, dispatch a `getCategoryError` action.

**Comment by m-hodges** [comment]
it appears there is a discrepancy between this ticket and the wiki: get foods by category on the wiki refers to the route /api/v1/category/:categoryName, this tick refers to the same functionality but with the route /api/v1/foods/category/:name.
