### ISSUE TITLE
Create 'Label' component

### ISSUE THREAD

**Issue by bryceknz** [pohutukawa-2019/foodlist#53]
Create a `Label` component that will receive `value` (numerical), and `type` (`'water'` or `'carbon'`) through props.  This will display the impact level (`'Extreme'`, `'High'`, `'Medium'`, or `'Low'`), inside a colored label. You will need to use the helper methods in `/client/utils/getLevel.js` to determine the impact level and coloring based on the type, and value passed in.

You will want to use [Semantic UI's Label component](https://react.semantic-ui.com/elements/label/) to show this information. Have a think about what will look the best - then run your ideas past one of the senior devs!

Speak to a dev lead if you need guidance about how to handle the functionality side of things.

**Comment by marvin-c** [comment]
noticed the following,
Label.jsx is renamed FoodLabel.jsx and Label.text.jsx is moved to components and renamed to FoodLabel.test.js
this ticket is also available on dev branch. found out when I tried to git pull origin dev.
