### ISSUE TITLE
Create AddFood component

### ISSUE THREAD

**Issue by bryceknz** [pohutukawa-2019/foodlist#9]
We're going to need an `AddFood` component that will show a form for the user to create the details for a new food.

>Input fields for 'name', 'CO2 output', and 'water usage'. Drop-down selector for 'food group'/'category'.

```js
{
  "name": "Dragonfruit",
  "category_id":  1,
  "carbon_output": 101,
  "water_usage": 88
}
```

How you render the form visually is up to you - but run your idea past your lead developers before implementing. Here's a hopefully helpful [reference](https://react.semantic-ui.com/collections/form/).

**Comment by iris-riddell** [comment]
This ticket is mostly complete (merged with `dev`), but there is a test that requires an action creator.
